### PR TITLE
Roll back v22 breaking changes

### PR DESCRIPTION
**Pull request by leannecornish-ft**
This is to roll back the v22 changes that were added to v21 accidentally.

### CODE REVIEW

**Comment by leannecornish-ft** [comment]
I think a rebase and merge would be best for this - please confirm.

**Comment by ivomurrell** [comment]
> I think a rebase and merge would be best for this - please confirm.

Yes, we probably want to rebase your changes onto the `v21` branch rather than having them based off of `main`?

**Review by apaleslimghost — APPROVED** [review]
just checking i've got the right end of the stick, this should be v21, with the recent changes, minus the v22 breaking changes? if that's the case, looks good

**Comment by leannecornish-ft** [comment]
> just checking i've got the right end of the stick, this should be v21, with the recent changes, minus the v22 breaking changes? if that's the case, looks good

Yes, exactly right. Thanks!

**Pull request merged**
