### PR TITLE
Fix incorrect cert paths

### PR DESCRIPTION
**Pull request by i-like-robots**
Not currently possible to use HTTPS 

CC @wheresrhys

### CODE REVIEW

**Comment by wheresrhys** [comment]
:+1:

**Comment by i-like-robots** [comment]
I can't figure out the broken test =/

**Comment by wheresrhys** [comment]
Also, please add a test to make sure the regression doesn't come back

**Comment by wheresrhys** [comment]
That broken test is an intermittent pain. Try running again

**Pull request merged**
