### PR TITLE
Update next-metrics

### PR DESCRIPTION
**Pull request by camillecroci**
This is to register the Insights Recommended Articles endpoint that is used in dotcom-pages ([PR](https://github.com/Financial-Times/next-metrics/pull/531))

### CODE REVIEW

**Comment by alexmuller** [comment]
👍 but would you give me a little bit of time to upgrade Tool Kit so that we can fix the release process? I'll try and get it done today!

**Review by apaleslimghost — APPROVED** [review]

**Comment by camillecroci** [comment]
@alexmuller does it mean I need to wait before merging? Or is it something to do when doing a release? Sorry i am not aware of the issue with the release

**Comment by alexmuller** [comment]
What I'd love is if we could:
- merge #789 and release it as a patch version (to make sure the release process is fixed)
- merge and release this PR

See here for more details on the broken process: https://financialtimes.slack.com/archives/C041V9QA7/p1697197538720119

**Review by alexmuller — APPROVED** [review]
I've got to run, if v28.0.7 shows up on npm (should be in the next few minutes) please merge and release this PR!

**Comment by camillecroci** [comment]
@alexmuller it looks like it did not do the release on npm if Im correct :/ https://www.npmjs.com/package/@financial-times/n-express

**Comment by alexmuller** [comment]
@camillecroci Sorry, I can take a look at this tomorrow or if you mention it in #cp-platforms-team they may be able to investigate. But they are also quite stretched today.

**Comment by alexmuller** [comment]
#794 Joel fixed it

**Comment by camillecroci** [comment]
@alexmuller woooooh, should I merge that at 4pm on a friday ? ( I wont, even if its tiny, I WONT)

**Pull request merged**
