### PR TITLE
Vary on correct anonymous user header

### PR DESCRIPTION
**Pull request by phamann**
As is causing caching issues :/

### CODE REVIEW

**Comment by matthew-andrews** [comment]
how did that happen?

**Comment by wheresrhys** [comment]
:+1:

**Comment by phamann** [comment]
Well strangely it seems we are still setting both: https://github.com/search?q=org%3AFinancial-Times+FT-Anonymous-User&type=Code

I will continue to investigate as to where'/why it's being removed. But want to ship fix in the interim.

**Comment by matthew-andrews** [comment]
+1

**Comment by matthew-andrews** [comment]
fyi this is a new major version…… might want to patch v15

**Pull request merged**
