### PR TITLE
product-selector -> products

### PR DESCRIPTION
**Pull request by commuterjoy**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
:+1: for the change, but what's this doing here?  can it be moved away in your refactor too?

**Comment by commuterjoy** [comment]
> but what's this doing here

It looks like it's flagging anonymous users to the controllers and templates.

I might be able to remove it, but applications can serve anonymous people - need to investigate.

**Comment by wheresrhys** [comment]
still needed @commuterjoy ?

**Comment by commuterjoy** [comment]
nah.

**Pull request closed without merging**
