### PR TITLE
Remove unused IP whitelist code

### PR DESCRIPTION
**Pull request by andygout**
The original intention was just to rename 'whitelist' -> 'allowlist' in line with [TGG: Address offensive and objectionable technology terms](https://docs.google.com/document/d/1v6z7_NkLFeYAFotTYB8C1OguO5iMHHLpAOv_yG5EKHI/edit#).

However, as per https://github.com/Financial-Times/n-express/pull/611, it transpires that the `ip-whitelist` module is not being employed whatsoever (https://github.com/search?q=user%3AFinancial-Times+ipWhitelist&type=Code) meaning we are in a position to remove the dead code, which is done in this PR.

### CODE REVIEW

**Comment by andygout** [comment]
Would others agree with a patch release?

**Review by apaleslimghost — APPROVED** [review]
did a bit more digging, looks like this used to be used as a fallback for backend keys, but it was removed three days after it was added back in 2017 and the code was never cleaned up https://github.com/Financial-Times/n-express/commit/453d0a11eba2f66e7bd60410b6595aa2b3d97558

**Comment by andygout** [comment]
Nice detective work.

Three and a half years without using it seems like sufficient assurance.

**Comment by apaleslimghost** [comment]
oh, just realised you should remove the `ip` package from `package.json` as well

**Comment by apaleslimghost** [comment]
nooooo one second too late

**Pull request merged**
